services:
  nuryanti-gims:
    build: .
    environment:
      - NODE_ENV=production
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - WHATSAPP_NUMBER=${WHATSAPP_NUMBER}
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nuryanti-gims.entrypoints=https'
      - 'traefik.http.routers.nuryanti-gims.rule=Host(`nuryantiislamicmontessori.com`)'
      - 'traefik.http.routers.nuryanti-gims.tls=true'
      - 'traefik.http.services.nuryanti-gims.loadbalancer.server.port=3000'

networks:
  proxy:
    external: true
